/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicStravaWebhookRouteImport } from './routes/api/public/strava-webhook'
import { Route as ApiPublicDailyBriefingRouteImport } from './routes/api/public/daily-briefing'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStravaWebhookRoute = ApiPublicStravaWebhookRouteImport.update({
  id: '/api/public/strava-webhook',
  path: '/api/public/strava-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyBriefingRoute = ApiPublicDailyBriefingRouteImport.update({
  id: '/api/public/daily-briefing',
  path: '/api/public/daily-briefing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/daily-briefing': typeof ApiPublicDailyBriefingRoute
  '/api/public/strava-webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/daily-briefing': typeof ApiPublicDailyBriefingRoute
  '/api/public/strava-webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/daily-briefing': typeof ApiPublicDailyBriefingRoute
  '/api/public/strava-webhook': typeof ApiPublicStravaWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/api/public/daily-briefing'
    | '/api/public/strava-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/api/public/daily-briefing'
    | '/api/public/strava-webhook'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/auth/callback'
    | '/api/public/daily-briefing'
    | '/api/public/strava-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicDailyBriefingRoute: typeof ApiPublicDailyBriefingRoute
  ApiPublicStravaWebhookRoute: typeof ApiPublicStravaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/strava-webhook': {
      id: '/api/public/strava-webhook'
      path: '/api/public/strava-webhook'
      fullPath: '/api/public/strava-webhook'
      preLoaderRoute: typeof ApiPublicStravaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-briefing': {
      id: '/api/public/daily-briefing'
      path: '/api/public/daily-briefing'
      fullPath: '/api/public/daily-briefing'
      preLoaderRoute: typeof ApiPublicDailyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicDailyBriefingRoute: ApiPublicDailyBriefingRoute,
  ApiPublicStravaWebhookRoute: ApiPublicStravaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
